// Generated by Roswaal, do not touch.

import * as TestActions from "./TestActions"
import { launchApp } from "../Launch"
import { RoswaalTestCase } from "../TestCase"
import { roswaalClient } from "../Client"

test("Roswaal can Siiiiiiiign In", async () => {
  const testCase = new RoswaalTestCase("Roswaal can Siiiiiiiign In", TestActions.beforeLaunch)
  // Roswaal is at the doooooooooor.
  testCase.appendAction(TestActions.haveRoswaalEnterHisNaaaaaaaaaame)
  // Roswaal is being blocked by securiiiiiiity.
  testCase.appendAction(TestActions.haveRoswaalEnterHisPaaaaaaaaassword)
  // Roswaal tries to access the ciiiiiiircus
  testCase.appendAction(TestActions.verifyThatRoswaalSignedInSucceeeeeeeessfully)
  await roswaalClient.run(testCase)
})
