/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:dfa4e3e1-c14a-4726-a397-47806a10791c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_DnTxqq3Il",
    "aws_user_pools_web_client_id": "3b8l148e1npdpkt366ha3gfjhh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3dm7tzc3ojd7rfeatbp4tpvi7i.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
