// Generated by Roswaal, do not touch.

import * as TestActions from "./TestActions"
import { launchApp } from "../Launch"
import { RoswaalTestCase } from "../TestCase"
import { roswaalClient } from "../Client"

test("Demo the roswaal tool", async () => {
  const testCase = new RoswaalTestCase("Demo the roswaal tool", TestActions.beforeLaunch)
  // Create test
  testCase.appendAction(TestActions.writeTheTestSpec)
  await roswaalClient.run(testCase)
})
