// Generated by Roswaal, do not touch.

import * as TestActions from "./TestActions"
import { launchApp } from "../Launch"
import { RoswaalTestCase } from "../TestCase"
import { roswaalClient } from "../Client"

test("Johnny Died", async () => {
  const testCase = new RoswaalTestCase("Johnny Died", TestActions.beforeLaunch)
  // Did you know that Johnny Died
  testCase.appendAction(TestActions.sendJohnnyToHell)
  // Close this PR
  testCase.appendAction(TestActions.thisWasJustATestOfTheToolJohnnyIsAliveAndWell)
  await roswaalClient.run(testCase)
})
