// Generated by Roswaal, do not touch.

export namespace TestLocations {
  export const SanFrancisco = {
    latitude: 37.7793807983398438,
    longitude: -122.4184265136718750
  }
  export const Sacramento = {
    latitude: 38.5815811157226562,
    longitude: -121.4936676025390625
  }
}
