// Generated by Roswaal, do not touch.

import { LocationCoordinate2D } from "TiFShared/domain-models/LocationCoordinate2D"

export const setUserLocation = async (coordinate: LocationCoordinate2D) => {
  await device.setLocation(coordinate.latitude, coordinate.longitude)
}

export namespace TestLocations {
  export const CayugaPark = {
    latitude: 37.7136039733886719,
    longitude: -122.4506225585937500
  }
  export const JohnMcLarenPark = {
    latitude: 37.7120208740234375,
    longitude: -122.4180908203125000
  }
  export const SantaCruzBoardwalkBeach = {
    latitude: 36.9641036987304688,
    longitude: -122.0167388916015625
  }
  export const Pyongyang = {
    latitude: 39.0344429016113281,
    longitude: 125.7417678833007812
  }
}
