// Generated by Roswaal, do not touch.

export namespace TestLocations {
  export const JohnMcLarenPark = {
    latitude: 37.7120208740234375,
    longitude: -122.4180908203125000
  }
  export const CayugaPark = {
    latitude: 37.7136039733886719,
    longitude: -122.4506225585937500
  }
}
