// Generated by Roswaal, do not touch.

import * as TestActions from "./TestActions"
import { launchApp } from "../Launch"
import { RoswaalTestCase } from "../TestCase"
import { roswaalClient } from "../Client"

test("Update Event", async () => {
  const testCase = new RoswaalTestCase("Update Event", TestActions.beforeLaunch)
  // Set Location to John McLaren Park
  testCase.appendAction(TestActions.setLocationToJohnMcLarenPark)
  // Paul creates outdoor dance lesson event in John McLaren Park next Sunday morning.
  testCase.appendAction(TestActions.havePaulCreateTheEventoutdoorDanceLessonInJohnMclarenParkNextSundayAt800Am)
  // Laura joins Paul's outdoor dance lesson event before it starts.
  testCase.appendAction(TestActions.haveLauraJoinTheoutdoorDanceLessonEvent)
  // Paul updates the time and location of the event to take place in Cayuga Park on Monday at noon.
  testCase.appendAction(TestActions.havePaulUpdateTheTimeAndLocationOfTheoutdoorDanceLessonEventToBeInCayugaParkOnMondayAt1200Pm)
  // Laura is notified that the time and location of the event have changed.
  testCase.appendAction(TestActions.verifyThatLauraWasNotifiedThatoutdoorDanceLessonWasUpdated)
  // Laura views the updated event.
  testCase.appendAction(TestActions.verifyThatLauraCanViewTheUpdatedEventDetailsFromTheNotification)
  await roswaalClient.run(testCase)
})
