// Generated by Roswaal, do not touch.

import * as TestActions from "./TestActions"
import { launchApp } from "../Launch"
import { RoswaalTestCase } from "../TestCase"
import { roswaalClient } from "../Client"

test("Blob begins his Journey!", async () => {
  const testCase = new RoswaalTestCase("Blob begins his Journey!", TestActions.beforeLaunch)
  // His name is Blob
  testCase.appendAction(TestActions.makeTheUsersNameBlob)
  // Blob is 20
  testCase.appendAction(TestActions.makeBlob20YearsOld)
  // Blob is ready to get started!
  testCase.appendAction(TestActions.verifyThatBlobCanBeginHisJourney!)
  await roswaalClient.run(testCase)
})
