// Generated by Roswaal, do not touch.

import * as TestActions from "./TestActions"
import { launchApp } from "../Launch"
import { RoswaalTestCase } from "../TestCase"
import { roswaalClient } from "../Client"

test("A really cool test!", async () => {
  const testCase = new RoswaalTestCase("A really cool test!", TestActions.beforeLaunch)
  // He is named Blob
  testCase.appendAction(TestActions.nameTheUserBlob)
  // Blob is 10
  testCase.appendAction(TestActions.makeBlob10YearsOld)
  await roswaalClient.run(testCase)
})
