// Generated by Roswaal, do not touch.

import * as TestActions from "./TestActions"
import { launchApp } from "../Launch"
import { RoswaalTestCase } from "../TestCase"
import { roswaalClient } from "../Client"

test("Blob Embarks on his new Journey!", async () => {
  const testCase = new RoswaalTestCase("Blob Embarks on his new Journey!", TestActions.beforeLaunch)
  // His name is Blob
  testCase.appendAction(TestActions.makeTheTravelersNameBlob)
  // Blob is 20
  testCase.appendAction(TestActions.makeBlob20YearsOld)
  // Blob is ready to embark!
  testCase.appendAction(TestActions.verifyThatBlobCanStartHisJourney!)
  await roswaalClient.run(testCase)
})
