// Generated by Roswaal, do not touch.

import * as TestActions from "./TestActions"
import { launchApp } from "../Launch"
import { RoswaalTestCase } from "../TestCase"
import { roswaalClient } from "../Client"

test("I am Rooooooooooswal!", async () => {
  const testCase = new RoswaalTestCase("I am Rooooooooooswal!", TestActions.beforeLaunch)
  // This is my first PRRRRRRRRRRR!
  testCase.appendAction(TestActions.youWillApprooooooooooveIt!)
  await roswaalClient.run(testCase)
})
