// Generated by Roswaal, do not touch.

import * as TestActions from "./TestActions"
import { launchApp } from "../Launch"
import { RoswaalTestCase } from "../TestCase"
import { roswaalClient } from "../Client"

test("My Cool Test!!!!", async () => {
  const testCase = new RoswaalTestCase("My Cool Test!!!!", TestActions.beforeLaunch)
  // I am Blob
  testCase.appendAction(TestActions.nameTheUserBlob)
  // I am 10
  testCase.appendAction(TestActions.makeBlob10YearsOld)
  // I have started!
  testCase.appendAction(TestActions.verifyThatBlobHasStartedTheJourney!)
  await roswaalClient.run(testCase)
})
